


services:
  postgresql:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  order-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgresql:5432/order_service
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8000
      RELOAD: "false"
      SERVER_WORKERS: 1
    depends_on:
      - postgresql
    restart: unless-stopped


volumes:
  postgres_data:
